=== utrymate/XML-beadand-/Utry Máté XML beadandó/2. rész/src/beadando.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="beadando" xmlns="beadando" elementFormDefault="qualified">
    <xs:element name="alkalmazasfejlesztes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="felhasznalok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="felhasznalo" type="felhasznaloTipus" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="megrendelok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="megrendelo" type="megrendeloTipus" minOccurs="0" maxOccurs="unbounded"/> 
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="alkalmazasok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alkalmazas" type="alkalmazasTipus" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="kivitelezesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kivitelezes" type="kivitelezesTipus" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="szoftverfejlesztok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="szoftverfejleszto" type="szoftverfejlesztoTipus" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
        <xs:key name="key1">
            <xs:selector xpath="felhasznalo" />
            <xs:field xpath="@fkod" />
        </xs:key>
        <xs:key name="key2">
            <xs:selector xpath="megrendelo" />
            <xs:field xpath="@mkod" />
        </xs:key>
        <xs:key name="key3">
            <xs:selector xpath="alkalmazas" />
            <xs:field xpath="@akod" />
        </xs:key>  
        <xs:key name="key4">
            <xs:selector xpath="szoftverfejleszto" />
            <xs:field xpath="@szkod" />
        </xs:key>
        
        <xs:keyref name="keyref1" refer="key1">
            <xs:selector xpath="megrendelo" />
            <xs:field xpath="@fkod" />
        </xs:keyref>
        <xs:keyref name="keyref2" refer="key2">
            <xs:selector xpath="alkalmazas" />
            <xs:field xpath="@mkod" />
        </xs:keyref> 
        <xs:keyref name="keyref3" refer="key3">
            <xs:selector xpath="kivitelezes" />
            <xs:field xpath="@akod" />
        </xs:keyref>
        <xs:keyref name="keyref4" refer="key4">
            <xs:selector xpath="kivitelezes" />
            <xs:field xpath="@szkod" />
        </xs:keyref>
    </xs:element>
    
    <xs:complexType name="felhasznaloTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="felhasznalonev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:int" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="megrendeloTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="telefon">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{2} [0-9]{3} [0-9]{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        
        <xs:attribute name="mkod" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z]*-[0-9]*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="fkod" type="xs:int" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="alkalmazasTipus">
        <xs:sequence>
			<xs:element name="nev" type="xs:string"/>
            <xs:element name="nyelv">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="CSharp"/>
                        <xs:enumeration value="Java"/>
                        <xs:enumeration value="HTML"/>
						<xs:enumeration value="PHP"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="akod" type="xs:int" use="required"/>
        <xs:attribute name="mkod" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z]*-[0-9]*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="kivitelezesTipus">
        <xs:sequence>
            <xs:element name="datum" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="akod" type="xs:int" use="required" />
        <xs:attribute name="szkod" type="xs:int" use="required" />
    </xs:complexType>
                
    <xs:complexType name="szoftverfejlesztoTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="lakcim" type="lakcimTipus"/>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:int" use="required"/>
    </xs:complexType>
                
    <xs:complexType name="lakcimTipus">
        <xs:sequence>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:maxInclusive value="333" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>     
</xs:schema>

=== utrymate/XML-beadand-/Utry Máté XML beadandó/2. rész/src/minta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="beadando.xsl"?>
<alkalmazasfejlesztes xmlns="beadando" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="beadando beadando.xsd ">
    
    <felhasznalok>
        <felhasznalo fkod="0">
            <nev>Utry Máté</nev>
            <felhasznalonev>utrymate</felhasznalonev>
        </felhasznalo>
        <felhasznalo fkod="1">
            <nev>Csabai Tibor</nev>
            <felhasznalonev>tibikepower</felhasznalonev>
        </felhasznalo>
        <felhasznalo fkod="2">
            <nev>Felhaszná Lóránt</nev>
            <felhasznalonev>usernamelori</felhasznalonev>
        </felhasznalo>
        <felhasznalo fkod="3">
            <nev>Us Ernő</nev>
            <felhasznalonev>ernokeasd</felhasznalonev>
        </felhasznalo>
    </felhasznalok>
    
    <megrendelok>
        <megrendelo mkod="LOLO-123" fkod="0">
            <nev>Rende Lőrinc</nev>
            <telefon>20 123 4567</telefon>
        </megrendelo>
        <megrendelo mkod="ORB-1" fkod="0">
            <nev>Megbíz Orbán</nev>
            <telefon>30 123 4567</telefon>
        </megrendelo>
        <megrendelo mkod="FA-52" fkod="1">
            <nev>Fa Szabolcs</nev>
            <telefon>70 123 4567</telefon>
        </megrendelo>
        <megrendelo mkod="LAJ-05" fkod="1">
            <nev>Lajos</nev>
            <telefon>20 111 1111</telefon>
        </megrendelo>
        <megrendelo mkod="NAGY-47352" fkod="2">
            <nev>Nagy Attila</nev>
            <telefon>30 111 1111</telefon>
        </megrendelo>
        <megrendelo mkod="KRISZ-123" fkod="3">
            <nev>Nagy Krisztián</nev>
            <telefon>70 111 1111</telefon>
        </megrendelo>
    </megrendelok>
    
    <alkalmazasok>
        <alkalmazas akod="0" mkod="LOLO-123">
            <nev>GTA 5</nev>
            <nyelv>CSharp</nyelv>
        </alkalmazas>
        <alkalmazas akod="1" mkod="LOLO-123">
            <nev>Neptun</nev>
            <nyelv>Java</nyelv>
        </alkalmazas>
        <alkalmazas akod="2" mkod="LOLO-123">
            <nev>Bajusz</nev>
            <nyelv>PHP</nyelv>
        </alkalmazas>
        <alkalmazas akod="3" mkod="ORB-1">
            <nev>Goat simulator</nev>
            <nyelv>Java</nyelv>
        </alkalmazas>
        <alkalmazas akod="4" mkod="FA-52">
            <nev>Windows XP</nev>
            <nyelv>HTML</nyelv>
        </alkalmazas>
        <alkalmazas akod="5" mkod="NAGY-47352">
            <nev>Ultimate Chess Game</nev>
            <nyelv>HTML</nyelv>
        </alkalmazas>
        <alkalmazas akod="6" mkod="LAJ-05">
            <nev>Go</nev>
            <nyelv>PHP</nyelv>
        </alkalmazas>
        <alkalmazas akod="7" mkod="KRISZ-123">
            <nev>Uncharted 4</nev>
            <nyelv>CSharp</nyelv>
        </alkalmazas>
    </alkalmazasok>
    
    <kivitelezesek>
        <kivitelezes akod="1" szkod="1">
            <datum>2004</datum>
        </kivitelezes>
        <kivitelezes akod="0" szkod="0">
            <datum>2006</datum>
        </kivitelezes>
        <kivitelezes akod="3" szkod="0">
            <datum>2010</datum>
        </kivitelezes>
        <kivitelezes akod="11" szkod="0">
            <datum>2011</datum>
        </kivitelezes>
        <kivitelezes akod="5" szkod="1">
            <datum>2003</datum>
        </kivitelezes>
        <kivitelezes akod="2" szkod="2">
            <datum>2005</datum>
        </kivitelezes>
        <kivitelezes akod="9" szkod="2">
            <datum>2012</datum>
        </kivitelezes>
        <kivitelezes akod="3" szkod="3">
            <datum>2015</datum>
        </kivitelezes>
        <kivitelezes akod="8" szkod="3">
            <datum>2016</datum>
        </kivitelezes>
        <kivitelezes akod="6" szkod="3">
            <datum>2018</datum>
        </kivitelezes>
    </kivitelezesek>
    
    <szoftverfejlesztok>
        <szoftverfejleszto szkod="0">
            <nev>Zolika</nev>
            <lakcim>
                <varos>Onga</varos>
                <utca>Kossuth Lajos</utca>
                <hazszam>45</hazszam>
            </lakcim>
        </szoftverfejleszto>
        <szoftverfejleszto szkod="1">
            <nev>Fejlesz Török</nev>
            <lakcim>
                <varos>Ankara</varos>
                <utca>Muszlim</utca>
                <hazszam>43</hazszam>
            </lakcim>
        </szoftverfejleszto>
        <szoftverfejleszto szkod="2">
            <nev>Teszt Elek</nev>
            <lakcim>
                <varos>Budapest</varos>
                <utca>Lajos</utca>
                <hazszam>123</hazszam>
            </lakcim>
        </szoftverfejleszto>
        <szoftverfejleszto szkod="3">
            <nev>Bill Gates</nev>
            <lakcim>
                <varos>California</varos>
                <utca>Bill Gates street</utca>
                <hazszam>222</hazszam>
            </lakcim>
        </szoftverfejleszto>
    </szoftverfejlesztok>
    
</alkalmazasfejlesztes>

=== utrymate/XML-beadand-/Utry Máté XML beadandó/2. rész/src/modositott.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="beadando.xsl"?><alkalmazasfejlesztes xmlns="beadando" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="beadando beadando.xsd">
    
    <felhasznalok>
        <felhasznalo fkod="0">
            <nev>Utry Máté</nev>
            <felhasznalonev>utrymate</felhasznalonev>
        </felhasznalo>
        <felhasznalo fkod="1">
            <nev>Tibci</nev>
            <felhasznalonev>powa</felhasznalonev>
        </felhasznalo>
        <felhasznalo fkod="2">
            <nev>Felhaszná Lóránt</nev>
            <felhasznalonev>usernamelori</felhasznalonev>
        </felhasznalo>
        <felhasznalo fkod="3">
            <nev>Us Ernő</nev>
            <felhasznalonev>ernokeasd</felhasznalonev>
        </felhasznalo>
    </felhasznalok>
    
    <megrendelok>
        <megrendelo fkod="0" mkod="LOLO-123">
            <nev>Rende Lőrinc</nev>
            <telefon>20 123 4567</telefon>
        </megrendelo>
        <megrendelo fkod="0" mkod="ORB-1">
            <nev>Megbíz Orbán</nev>
            <telefon>30 123 4567</telefon>
        </megrendelo>
        <megrendelo fkod="1" mkod="FA-52">
            <nev>Fa Szabolcs</nev>
            <telefon>70 123 4567</telefon>
        </megrendelo>
        <megrendelo fkod="1" mkod="LAJ-05">
            <nev>Lajos</nev>
            <telefon>20 111 1111</telefon>
        </megrendelo>
        <megrendelo fkod="2" mkod="NAGY-47352">
            <nev>Nagy Attila</nev>
            <telefon>30 111 1111</telefon>
        </megrendelo>
        <megrendelo fkod="3" mkod="KRISZ-123">
            <nev>Nagy Krisztián</nev>
            <telefon>70 111 1111</telefon>
        </megrendelo>
    <megrendelo fkod="1" mkod="2">
      <nev>Tib</nev>
      <telefon>201231239</telefon>
    </megrendelo>
  </megrendelok>
    
    <alkalmazasok>
        <alkalmazas akod="0" mkod="LOLO-123">
            <nev>GTA 5</nev>
            <nyelv>CSharp</nyelv>
        </alkalmazas>
        <alkalmazas akod="1" mkod="LOLO-123">
            <nev>Neptun</nev>
            <nyelv>Java</nyelv>
        </alkalmazas>
        <alkalmazas akod="2" mkod="LOLO-123">
            <nev>Bajusz</nev>
            <nyelv>PHP</nyelv>
        </alkalmazas>
        <alkalmazas akod="3" mkod="ORB-1">
            <nev>Goat simulator</nev>
            <nyelv>Java</nyelv>
        </alkalmazas>
        <alkalmazas akod="4" mkod="FA-52">
            <nev>Windows XP</nev>
            <nyelv>HTML</nyelv>
        </alkalmazas>
        <alkalmazas akod="5" mkod="NAGY-47352">
            <nev>Ultimate Chess Game</nev>
            <nyelv>HTML</nyelv>
        </alkalmazas>
        <alkalmazas akod="6" mkod="LAJ-05">
            <nev>Go</nev>
            <nyelv>PHP</nyelv>
        </alkalmazas>
        <alkalmazas akod="7" mkod="KRISZ-123">
            <nev>Uncharted 4</nev>
            <nyelv>CSharp</nyelv>
        </alkalmazas>
    </alkalmazasok>
    
    <kivitelezesek>
        <kivitelezes akod="1" szkod="1">
            <datum>2004</datum>
        </kivitelezes>
        <kivitelezes akod="0" szkod="0">
            <datum>2006</datum>
        </kivitelezes>
        <kivitelezes akod="3" szkod="0">
            <datum>2010</datum>
        </kivitelezes>
        <kivitelezes akod="11" szkod="0">
            <datum>2011</datum>
        </kivitelezes>
        <kivitelezes akod="5" szkod="1">
            <datum>2003</datum>
        </kivitelezes>
        <kivitelezes akod="2" szkod="2">
            <datum>2005</datum>
        </kivitelezes>
        <kivitelezes akod="9" szkod="2">
            <datum>2012</datum>
        </kivitelezes>
        <kivitelezes akod="3" szkod="3">
            <datum>2015</datum>
        </kivitelezes>
        <kivitelezes akod="8" szkod="3">
            <datum>2016</datum>
        </kivitelezes>
        <kivitelezes akod="6" szkod="3">
            <datum>2018</datum>
        </kivitelezes>
    </kivitelezesek>
    
    <szoftverfejlesztok>
        <szoftverfejleszto szkod="0">
            <nev>Zolika</nev>
            <lakcim>
                <varos>Onga</varos>
                <utca>Kossuth Lajos</utca>
                <hazszam>45</hazszam>
            </lakcim>
        </szoftverfejleszto>
        <szoftverfejleszto szkod="1">
            <nev>Fejlesz Török</nev>
            <lakcim>
                <varos>Ankara</varos>
                <utca>Muszlim</utca>
                <hazszam>43</hazszam>
            </lakcim>
        </szoftverfejleszto>
        <szoftverfejleszto szkod="2">
            <nev>Teszt Elek</nev>
            <lakcim>
                <varos>Budapest</varos>
                <utca>Lajos</utca>
                <hazszam>123</hazszam>
            </lakcim>
        </szoftverfejleszto>
        <szoftverfejleszto szkod="3">
            <nev>Bill Gates</nev>
            <lakcim>
                <varos>California</varos>
                <utca>Bill Gates street</utca>
                <hazszam>222</hazszam>
            </lakcim>
        </szoftverfejleszto>
    </szoftverfejlesztok>
    
</alkalmazasfejlesztes>
